# Especialització de DataScience de la IT ACADEMY
### *Sprint2 - Tasca 4 - Exercici 1*
#### **Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.**

#### Alumne: Jorge Prieto Data: 16/02/2022

In [2]:
import numpy as np

In [3]:
#Funció per treure el valors estadistic d'una funció
def estadisticaArray(array):

    if (np.shape(array)[0]) == 1:
        print("Resum estadistic del array")
        print("array: \n",array)            
        print("Valor major del array: ",np.max(array)) #Valor major del array
        print("Valor menor del array: ",np.min(array)) #Valor menor del array
        print("Valor mitja del array: ",np.mean(array)) 
        print("Mitjana del array: ",np.median(array))     
        print("Desviació estandar del array:",np.std(array))
    else:
        print("Error: l'array no es unidimensional")

In [4]:
array1 = 10*np.round(np.random.random((1,20)),3)
array1

array([[0.99, 4.54, 9.08, 5.96, 7.39, 7.39, 0.12, 1.25, 5.43, 2.58, 1.47,
        7.81, 2.83, 1.11, 9.11, 8.69, 5.34, 2.47, 4.99, 8.7 ]])

In [5]:
estadisticaArray(array1)

Resum estadistic del array
array: 
 [[0.99 4.54 9.08 5.96 7.39 7.39 0.12 1.25 5.43 2.58 1.47 7.81 2.83 1.11
  9.11 8.69 5.34 2.47 4.99 8.7 ]]
Valor major del array:  9.11
Valor menor del array:  0.12
Valor mitja del array:  4.8625
Mitjana del array:  5.165
Desviació estandar del array: 2.997805655808928


In [6]:
array2 = np.ones((2,2))
array2

array([[1., 1.],
       [1., 1.]])

In [7]:
estadisticaArray(array2)

Error: l'array no es unidimensional


### *Sprint2 - Tasca 4 - Exercici 2*
#### **Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.**

In [8]:
import numpy as np

def creaArrayNxN(arg):
    array = np.random.randint(0,101, size=(arg,arg))
    return (array)

In [9]:
array = np.random.randint(0,101, size=(3,3))
print (array)

[[ 3 64 63]
 [57 71 76]
 [25 24 52]]


In [10]:
array = creaArrayNxN (3)
array

array([[18, 98, 85],
       [64,  9, 70],
       [36, 35, 62]])

### *Sprint2 - Tasca 4 - Exercici 3*
#### **Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.**

In [11]:
for i in array:
    print(np.sum(i))

201
143
133


In [12]:
import numpy as np

def calculaSumaFilasColumnasArray(arr):
    for i in arr:
        print("Suma Fila:",i,"es igual a",np.sum(i))
    arrT = np.transpose(arr)
    for i in arrT:
        print("Suma Columna:",i,"es igual a",np.sum(i))


In [13]:
array

array([[18, 98, 85],
       [64,  9, 70],
       [36, 35, 62]])

In [14]:
calculaSumaFilasColumnasArray(array)

Suma Fila: [18 98 85] es igual a 201
Suma Fila: [64  9 70] es igual a 143
Suma Fila: [36 35 62] es igual a 133
Suma Columna: [18 64 36] es igual a 118
Suma Columna: [98  9 35] es igual a 142
Suma Columna: [85 70 62] es igual a 217


### *Sprint2 - Tasca 4 - Exercici 4*
#### **Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.**

In [16]:
arr1 = np.random.randint(0,10, size=(1,3))
arr1

array([[7, 4, 3]])

In [17]:
arr2 = np.random.randint(0,10, size=(1,3))
arr2

array([[4, 4, 3]])

#### Càlcul manual del coeficient de Correlació de Pearson ####
##### Indica la correlació de les dos matrius en rang (-1 a 1): 
##### 1: matrius iguals (correlació total directa)
##### -1: matrius inverses amb igual modul (correlació total inversa)
##### 0: matrius totalment descorrelacionades

In [36]:
import numpy as np
import math

def coeficientCorrelacio(args1,args2):
    #Càlcul valors mitjans
    arrayMedia1 = np.mean(args1) 
    arrayMedia2 = np.mean(args2) 
    
    #Càlcul de les covariances
    arrayCov = np.cov(arr1,arr2)
    
    #Covariança entre arrays 1 i 2
    Cov12 = arrayCov[0,1]
    Cov1 = arrayCov[0,0]
    Cov2 = arrayCov[1,1]
    
    #càlcul del coeficient de Pearson
    coefPearson = Cov12/(math.sqrt(Cov1*Cov2))
    return coefPearson

In [39]:
coefCorrelacio = coeficientCorrelacio(arr1,arr2)
print("Coeficient de correlació dels arrays: ",coefCorrelacio)

Coeficient de correlació dels arrays:  0.6933752452815366


In [41]:
coefCorrelacioNumpy = (np.corrcoef(arr1,arr2)[0,1])
print("Coeficient de correlació del arrays: ",coefCorrelacioNumpy)     
#print(np.corrcoef(arr1,arr2))

Coeficient de correlació del arrays:  0.6933752452815366


In [42]:
DiffCoefCorr = coefCorrelacio - coefCorrelacioNumpy
DiffCoefCorr

0.0